AssetLibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload_form/',include('upload_form.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload_form/urls.py
from django.urls import path
from . import views


app_name = 'upload_form'
urlpatterns = [
    path('upload/',views.upload, name='upload'),
    path('list/',views.list, name='list'),
    path('file_del/',views.file_del,name = 'file_del')
]

upload_form/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import post_delete
from django.dispatch import receiver
import os
import sys
# Create your models here.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

CATEGORY_CHOICES = (
    ("テクスチャ", 'テクスチャ'),
    ('モデル', 'モデル'),
    ('エフェクト', 'エフェクト'),
)


class File(models.Model):
    # 画像のモデル
    class Meta:
        # モデル自体を表す文字列
        verbose_name = 'ファイル'
        verbose_name_plural = 'ファイル'
        ordering = ['-upload_time']
    owner = models.CharField(max_length=20)
    file_name = models.CharField(max_length=50)
    upload_time = models.DateTimeField(default=datetime.now)
    projects_name = models.CharField(max_length=20)
    file_path = models.CharField(max_length=100)
    thumbnail_path = models.CharField(max_length=100)
    extension = models.CharField(max_length=10)
    category = models.CharField(
        max_length=5, choices=CATEGORY_CHOICES, default=None)
    description = models.CharField(max_length=100, blank=True)
    #

    def __str__(self):
        return self.file_name


# モデル削除後に`file_field`を削除する。
@receiver(post_delete, sender=File)
def delete_file(sender, instance, **kwargs):
    try:
        # ドライブレターを消すためにスライシング
        file_path = os.path.join(BASE_DIR, instance.file_path[1:])
        os.remove(file_path)
    except FileNotFoundError:
        print('File not found')

    if instance.thumbnail_path == 'https://user-images.githubusercontent.com/48968940/74902177-970dbf00-53e8-11ea-94d5-a93d440ba732.jpg':
        # サムネがもともとなかった場合はreturn
        return
    try:
        # ドライブレターを消すためにスライシングして合体
        thumbnail_path = os.path.join(BASE_DIR, instance.thumbnail_path[1:])
        os.remove(thumbnail_path)
    except FileNotFoundError:
        print('File not found')

upload_form/forms.py
from django import forms
from . import models

CATEGORY_CHOICES = (
    ('Textures', 'Textures'),
    ('Models', 'Models'),
    ('Effects', 'Effects'),
)

class ThumbnailForm(forms.Form):
    thumbnail = forms.FileField(label='サムネイル（任意）',required=False)

class OwnerForm(forms.Form):
    owner= forms.CharField(max_length=10,label='投稿者')

class ProjectsForm(forms.Form):
    projects= forms.CharField(max_length=100,label='プロジェクト名')


class FileForm(forms.Form):
    file = forms.FileField(label='ファイル')

class FileNameSearchForm(forms.Form):
   file_name_search = forms.CharField(min_length=2, max_length=100,label='ファイル名検索',required=False)


class CategoryChoiceForm(forms.Form):
    category = forms.ChoiceField(label='カテゴリ',widget=forms.Select,choices=CATEGORY_CHOICES)

class DescriptionForm(forms.Form):
    description= forms.CharField(max_length=100,label='説明',required=False)

upload_form/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ThumbnailForm, OwnerForm, ProjectsForm, FileForm,\
    FileNameSearchForm, CategoryChoiceForm, DescriptionForm
from .models import File
from datetime import datetime
from PIL import Image, ImageFilter
from psd_tools import PSDImage
import sys
import os

# ファイルを保存するパス
UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'
# サムネイルのパス
THUMBNAIL_DIR = os.path.dirname(os.path.abspath(
    __file__)) + '/static/files/thumbnail/'


def upload(request):
    """
    FileFieldを使わずにopen(path,'wb')でコピーしている
    サムネイル作成対応
    18/10/22 メモ: 現在フォームを個別に設定しているが一つのクラスにまとめてforループで処理したほうがよさそう・・
    """
    if not request.method == 'POST':  # methodが'POST'ではない　＝最初のページ表示時の処理
        return render(request, 'upload_form/upload.html', {
            'FileForm': FileForm(),
            'ThumbnailForm': ThumbnailForm(),
            'OwnerForm': OwnerForm(),
            'ProjectsForm': ProjectsForm(),
            'CategoryChoiceForm': CategoryChoiceForm(),
            'DescriptionForm': DescriptionForm(),
            # 'images': ImageFile.objects.all(),
        })

    """パス作成してファイルコピー"""
    # リクエストオブジェクト取得
    file = request.FILES['file']
    try:
        thumbnail = request.FILES['thumbnail']
    except:
        thumbnail = ''
    # ファイルをアップロードする場所
    path = os.path.join(UPLOADE_DIR, file.name)
    # 拡張子を分離
    root, ext = os.path.splitext(path)

    # サムネイル用のパス
    thumbnail_path = os.path.join(THUMBNAIL_DIR, file.name)
    thumbnail_root, thumbnail_ext = os.path.splitext(thumbnail_path)
    thumbnail_root = thumbnail_root + "_thumbnail"
    thumbnail_path = thumbnail_root + thumbnail_ext
    if os.path.exists(path):
        # すでに同じ名前のファイルが存在する場合、ファイル名の最後に日付を書き足して保存する
        path = root + '_' + datetime.now().strftime('%Y%m%d%H%M%S') + ext
        thumbnail_path = thumbnail_root + '_' + \
            datetime.now().strftime('%Y%m%d%H%M%S') + ext

    # ファイルをコピーする
    destination = open(path, 'wb')
    for chunk in file.chunks():
        destination.write(chunk)
    destination.close()

    """
    サムネ作成
    """
    # そのファイル自体からサムネイルを作成できるもののリスト
    image_file_extension = ['.jpg', '.png', '.bmp', '.tga']
    if thumbnail:
        # サムネイルがアップされているときはコピーする
        destination = open(thumbnail_path, 'wb')
        for chunk in thumbnail.chunks():
            destination.write(chunk)
        destination.close()
    elif ext == '.psd':
        # PSDのときサムネイル作成
        thumbnail_root, thumbnail_ext = os.path.splitext(thumbnail_path)
        # サムネイルのパスの拡張子をjpgにしておく
        thumbnail_path = thumbnail_root + ".jpg"
        psd = PSDImage.load(path)
        merged_image = psd.as_PIL()
        merged_image.thumbnail((512, 512), Image.ANTIALIAS)
        merged_image.save(thumbnail_path)
    elif ext in image_file_extension:
        # 画像ファイルの場合サムネイルを作成を試みる
        try:
            thumbnail_root, thumbnail_ext = os.path.splitext(thumbnail_path)
            # サムネイルのパスの拡張子をjpgにしておく
            thumbnail_path = thumbnail_root + ".jpg"
            # サムネイルをファイルから作成する
            img = Image.open(path)
            # resizeではなくthumbnailを利用して縮小
            img.thumbnail((512, 512), Image.ANTIALIAS)
            # リサイズ後の画像を保存
            img.save(thumbnail_path, 'JPEG', quality=100, optimize=True)
        except:
            # Pillowが画像処理できなかった場合の処理
            print('Pillow can not create thumbnail image..')
            thumbnail_path = ''
    else:
        # サムネイルを作成できない場合
        thumbnail_path = ''

    """データベース更新"""
    file_model = File()
    file_path = os.path.join('/static/files/'+os.path.basename(path))
    file_model.file_path = file_path
    # サムネイル実装
    if thumbnail_path:
        file_model.thumbnail_path = os.path.join(
            '/static/files/thumbnail/'+os.path.basename(thumbnail_path))
    else:
        # サムネイルがないときはNOTHUMBNAIL
        file_model.thumbnail_path = 'https://user-images.githubusercontent.com/48968940/74902177-970dbf00-53e8-11ea-94d5-a93d440ba732.jpg'

    file_model.file_name = os.path.basename(path)
    file_model.owner = request.POST['owner']
    file_model.projects_name = request.POST['projects']
    file_model.category = request.POST['category']
    file_model.description = request.POST['description']
    file_model.extension = ext

    file_model.save()

    return redirect('upload_form:list')


def list(request):
    """
    フィルター実装
    ファイル名の検索フォーム実装
    リストのフィルターフォームからのPOSTを受け取って、フィルタリングする
    """
    # クエリセット作成
    files = File.objects.all()
    extension = File.objects.values(
        'extension').order_by('extension').distinct()
    projects_name = File.objects.values(
        'projects_name').order_by('projects_name').distinct()
    owner = File.objects.values('owner').order_by('owner').distinct()

    """GETの内容を取得してフィルタリングする"""
    category = request.GET.get('category')

    q_file_name_search = request.GET.get('file_name_search')
    q_ext = request.GET.get('extension')
    q_owner = request.GET.get('owner')
    q_projects_name = request.GET.get('projects_name')
    # q_category = request.POST['category']
    # フィルタリングする
    if category and not category == 'AssetLibrary':
        files = files.filter(category__contains=category)
    if q_file_name_search:
        files = files.filter(file_name__contains=q_file_name_search)
    if q_ext:
        files = files.filter(extension__contains=q_ext)
    if q_owner:
        files = files.filter(owner__contains=q_owner)
    if q_projects_name:
        files = files.filter(projects_name__contains=q_projects_name)

    return render(request, 'upload_form/list.html', {
        'FileNameSearchForm': FileNameSearchForm(),
        'files': files,
        'extension': extension,
        'projects_name': projects_name,
        'owner': owner,
    })


def file_del(request):
    """ファイルの削除"""
    if not request.method == 'POST':  # methodが'POST'ではない　＝最初のページ表示時の処理
        return redirect('upload_form:list')

    del_id = request.POST['del_id']
    file = get_object_or_404(File, pk=del_id)
    file.delete()
    return redirect('upload_form:list')

upload_form/templates/upload_form/base.html
<!DOCTYPE html>
{% load static %}



<html lang="ja">

<head>
  <meta charset="utf-8">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>
    {% block title %}
    {% endblock %}
  </title>
</head>

<body>
  {% block body %}
  {% endblock %}
  <link rel="stylesheet" type="text/css" href="{% static 'upload_form/css/upload_form_style.css' %}" />
</body>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

</html>

upload_form/templates/upload_form/list.html
{% extends "upload_form/base.html" %}

{% block title %}
アセット一覧
{% endblock %}

{% block body %}
<div class="container">

  <div class="right_style">
    <div>
      <ul class="cp_list">
        <li>
          <a href="/upload_form/list">All</a>
        </li>
        <li>
          <a href="/upload_form/list?category=Textures">Textures</a>
        </li>
        <li>
          <a href="/upload_form/list?category=Effects">Effects</a>
        </li>
        <li>
          <a href="/upload_form/list?category=Models">Models</a>
        </li>
      </ul>
    </div>

    <div class="filter_style">
      <form action={% url 'upload_form:list' %} method="GET">
        <!-- フィルター実装 -->
        <p>
          {# 検索フォーム実装 #}
          {{ FileNameSearchForm }}
          <input type='submit' value='検索' />
        </p>

        <p>
          拡張子：
          <select name="extension">
            {% for e in extension %}
            <!-- データベースから拡張子の種類のリストを取ってきてフィルターのリストを作成する -->
            <option value="{{e.extension}}">{{e.extension}}</option>
            {% endfor %}
            <option value="" selected>すべて</option>
          </select>
        </p>
        <p>
          プロジェクト名 :
          <select name="projects_name">
            {% for p in projects_name %}
            <!-- データベースから拡張子の種類のリストを取ってきてフィルターのリストを作成する -->
            <option value="{{p.projects_name}}">{{p.projects_name}}</option>
            {% endfor %}
            <option value="" selected>すべて</option>
          </select>
        </p>
        <p>
          アップロード者 :
          <select name="owner">
            {% for o in owner %}
            <!-- データベースから拡張子の種類のリストを取ってきてフィルターのリストを作成する -->
            <option value="{{o.owner}}">{{o.owner}}</option>
            {% endfor %}
            <option value="" selected>すべて</option>
          </select>
        </p>
        <input type="submit" value="絞り込み">
      </form>
    </div>

    <div>
      <a href={% url 'upload_form:upload'%} class="btn btn-outline-primary btn-sm">アップロードする！</a>
    </div>
  </div>
  <!-- ここからリスト表示 -->
  <div class="row row-eq-height grid_style">
    {% for file in files  %}
    <div class="col-lg-3 col-md-4 col-sm-6 thumbnail_style text-center col-md-offset-2">
      <!-- クリックする画像イメージ　サムネイル -->
      <img src="{{ file.thumbnail_path}}" class="img-responsive thumbnail aligncenter size-full grid_img thumbnail_img"
        data-toggle="modal" data-target="#image-modal{{file.pk}}" style="cursor:pointer" />
    </div>
    <!-- Modal -->
    <div class="modal fade" id="image-modal{{file.pk}}" tabindex="-1" role="dialog" aria-labelleady="myLargeModalLabel">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <!-- コンテンツの中身 -->

          <div class="modal-header">
            <!-- ヘッダー部分 -->
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body modal-img_body">
            <!-- body部分  -->

            <div class="modal-img_body_img">
              <!-- 画像配置  -->
              <img src="{{file.thumbnail_path}}" class="aligncenter img-responsive click_img" />
            </div>

            <div class="modal-img_body_download">
              <!--  ダウンロードボタン配置  -->
              <a class="btn btn-primary btn-block" role="button" href="{{ file.file_path}}"
                download="{{ file.file_name}}">ダウンロード</a>
            </div>

            <ul class="modal-img_body_textfull">
              <!-- 画像の詳細情報表示 -->
              <li class="modal-img_body_text_heading">詳細</li>
              <li> &nbsp; </li>
              <li><strong>ファイル名：</strong> {{file.file_name}}</li>
              <li><strong>拡張子：</strong> {{file.extension}}</li>
              <li><strong>アップロード者：</strong>{{file.owner}}</li>
              <li><strong>アップロード日時：</strong>{{file.upload_time}}</li>
              <li><strong>プロジェクト：</strong>{{file.projects_name}}</li>
              <li><strong>カテゴリ：</strong>{{file.category}}</li>
              <li><strong>説明：</strong>{{file.description}}</li>
            </ul>

          </div>

          <div class="modal-footer modal-img_footer">
            <!-- フッター部分　テキスト表示  -->
            <!-- 削除ボタン -->
            <form action={% url 'upload_form:file_del' %} method="POST">
              {% csrf_token %}
              <button type='submit' class='btn btn-danger del_button' name='del_id' value={{file.id}}>削除</button>
            </form>
            <!-- モーダルウィンドウを閉じるボタン -->
            <button type="buton" class="btn btn-success" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

</div>


{% endblock %}

upload_form/templates/upload_form/upload.html
{% extends "upload_form/base.html" %}

{% block title %}
  アップロード画面
{% endblock %}

{% block body %}
<div class="upload_style" >
  <form action= {% url 'upload_form:upload' %} method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
    {{ FileForm }}
    </p>
    <p>
      {{ ThumbnailForm }}
    </p>
    <p>
    {{ OwnerForm }}
    </p>
    <p>
    {{ProjectsForm}}
    </p>
    <p>
    {{CategoryChoiceForm}}
    </p>
    <p>
    {{DescriptionForm}}
    </p>
    <input type="submit" value="アップロード">
  </form>
</div>
{% endblock %}